---
name: Molecule Test
"on":
  push:
    branches:
      - "feature/inprogress"
permissions:
  contents: write
jobs:
  ansible_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade wheel setuptools
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f roles/requirements.yml ]; then ansible-galaxy install -r roles/requirements.yml -f; fi
      - name: Test
        run: |
          ansible-lint play_silent.yml
          ansible-lint play_interactive.yml
