---
- name: Add host
  hosts: localhost
  tasks:
    - name: "Include arpanrec.terraform_cloud_management"
      ansible.builtin.include_role:
        name: "arpanrec.terraform_cloud_management"
      vars:
        rl_tef_org_name: arpanrec
        rl_tef_org_email: me@arpanrec.com
        rl_tef_api_collaborator_auth_policy: two_factor_mandatory
        rl_tef_workspaces:
          - rl_tef_workspace_name: paas_aws
            auto_apply: 1
            execution_mode: local
          - rl_tef_workspace_name: paas_linode
            auto_apply: 1
            execution_mode: local
