---
name: Release

"on":
  push:

jobs:
  github_release:
    name: GitHub Release
    permissions:
      contents: write
      packages: write
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: "0"

      - name: Setup Node.js 18.16.0
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18.16.0
          cache: "npm"

      - name: Run symantic release
        run: |+
          npm install
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
